version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "[Dependabot]"
    labels:
      - "skip-release"
      - "dependencies"