name: quarkus-mvc

services:

#  backend:
#    build: .
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"

  jaeger:
    image: jaegertracing/jaeger:2.1.0
    ports:
      - "16686:16686"
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.116.1
    depends_on:
      - jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
      - "3000:3000"
    volumes:
      - "./collector.yaml:/etc/otelcol-contrib/config.yaml"

  prometheus:
    image: prom/prometheus:v3.0.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml