package com.truelayer.java.integration;

import static com.github.tomakehurst.wiremock.client.WireMock.*;
import static com.truelayer.java.Constants.HeaderNames.*;
import static com.truelayer.java.TestUtils.UUID_REGEX_PATTERN;

import com.truelayer.java.Constants;
import com.truelayer.java.TestUtils.RequestStub;
import com.truelayer.java.http.entities.Headers;
import com.truelayer.java.payments.entities.CreatePaymentRequest;
import java.util.Collections;
import lombok.SneakyThrows;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("HTTP Headers management integration tests")
public class HttpHeadersManagementTests extends IntegrationTests {

    @SneakyThrows
    @Test
    @DisplayName("Should send auto generated headers for idempotency and signature")
    public void shouldSendAutoGeneratedIdempotencyKey() {
        RequestStub.New()
                .method("post")
                .path(urlPathEqualTo("/connect/token"))
                .status(200)
                .bodyFile("auth/200.access_token.json")
                .build();
        CreatePaymentRequest paymentRequest = CreatePaymentRequest.builder().build();

        tlClient.payments().createPayment(paymentRequest).get();

        verifyGeneratedToken(Collections.singletonList(Constants.Scopes.PAYMENTS));
        verify(postRequestedFor(urlPathEqualTo("/payments"))
                .withHeader(IDEMPOTENCY_KEY, matching(UUID_REGEX_PATTERN.pattern()))
                .withHeader(TL_SIGNATURE, matching(".+")));
    }

    @SneakyThrows
    @Test
    @DisplayName("Should send custom provided headers without triggering default auto-generation")
    public void shouldSendAProvidedCustomHeadersWithoutAutoGeneration() {
        RequestStub.New()
                .method("post")
                .path(urlPathEqualTo("/connect/token"))
                .status(200)
                .bodyFile("auth/200.access_token.json")
                .build();
        CreatePaymentRequest paymentRequest = CreatePaymentRequest.builder().build();
        String idempotencyKey = "custom-key";
        String signature = "custom-signature";

        tlClient.payments()
                .createPayment(
                        Headers.builder()
                                .signature(signature)
                                .idempotencyKey(idempotencyKey)
                                .enablePagination()
                                .build(),
                        paymentRequest)
                .get();

        verifyGeneratedToken(Collections.singletonList(Constants.Scopes.PAYMENTS));
        verify(postRequestedFor(urlPathEqualTo("/payments"))
                .withHeader(TL_ENABLE_PAGINATION, equalTo("true"))
                .withHeader(TL_SIGNATURE, equalTo(signature))
                .withHeader(IDEMPOTENCY_KEY, equalTo(idempotencyKey)));
    }
}
