package com.truelayer.java.entities;

import static com.truelayer.java.entities.HostedPageType.HP2;
import static com.truelayer.java.entities.HostedPageType.HPP;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum ResourceType {
    // TODO: can this be deprecated? We should leverage the HPP URI generated by the payments-gateway instead.
    // note that deprecating would probably mean creating a new type for our test utils
    PAYMENT("payments", "payment_id", HPP),

    MANDATE("mandates", "mandate_id", HPP),
    PAYOUT("payouts", "payout_id", HP2);

    private final String hppLinkPath;
    private final String hppLinkQueryParameter;
    private final HostedPageType hostedPageType;
}
