name: Create release

on:
  push:
    tags:
      - "**"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Lint
        run: ./gradlew spotlessJavaCheck
      - name: Build
        run: ./gradlew build -x test
      - name: Unit tests
        run: ./gradlew unit-tests
      - name: Integration tests
        run: ./gradlew integration-tests
      - name: Acceptance tests in sandbox environment
        env:
          TL_CLIENT_ID: ${{ secrets.ACCEPTANCE_TEST_CLIENT_ID }}
          TL_CLIENT_SECRET: ${{ secrets.ACCEPTANCE_TEST_CLIENT_SECRET }}
          TL_SIGNING_KEY_ID: ${{ secrets.ACCEPTANCE_TEST_SIGNING_KEY_ID }}
          TL_SIGNING_PRIVATE_KEY: ${{ secrets.ACCEPTANCE_TEST_SIGNING_PRIVATE_KEY }}
        run: ./gradlew acceptance-tests
      - name: Create release
        uses: softprops/action-gh-release@v1
      - name: Publish package
        run: ./gradlew -Pversion=${GITHUB_REF##*/} publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}