name: Scheduled acceptance tests

on:
  schedule:
    - cron: "0 7-19/2 * * *" # every 2 hours between 10 and 20 (UTC)

jobs:
  scheduled-acceptance-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Acceptance tests in sandbox environment
        env:
          TL_CLIENT_ID: ${{ secrets.ACCEPTANCE_TEST_CLIENT_ID }}
          TL_CLIENT_SECRET: ${{ secrets.ACCEPTANCE_TEST_CLIENT_SECRET }}
          TL_SIGNING_KEY_ID: ${{ secrets.ACCEPTANCE_TEST_SIGNING_KEY_ID }}
          TL_SIGNING_PRIVATE_KEY: ${{ secrets.ACCEPTANCE_TEST_SIGNING_PRIVATE_KEY }}
        run: ./gradlew acceptance-tests