name: Scheduled acceptance tests

on:
  schedule:
    - cron: "0 7-19/2 * * *" # every 2 hours between 10 and 20 (UTC)

jobs:
  scheduled-acceptance-tests:
    name: Scheduled acceptance tests in Sandbox environment
    uses: ./.github/workflows/acceptance-tests.yml
    secrets:
      tl_client_id: ${{ secrets.ACCEPTANCE_TEST_CLIENT_ID }}
      tl_client_secret: ${{ secrets.ACCEPTANCE_TEST_CLIENT_SECRET }}
      tl_signing_key_id: ${{ secrets.ACCEPTANCE_TEST_SIGNING_KEY_ID }}
      tl_signing_private_key: ${{ secrets.ACCEPTANCE_TEST_SIGNING_PRIVATE_KEY }}
  notify-slack-channel-on-failures:
    name: Notify Slack channel on failures
    needs: scheduled-acceptance-tests
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK # type is required for custom payloads