name: test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      TL_CLIENT_ID: ${{ secrets.ACCEPTANCE_TEST_CLIENT_ID }}
    steps:
      - name: test
        run: echo $TL_CLIENT_ID
