name: test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ${{ secrets.ACCEPTANCE_TEST_CLIENT_ID }}