# Workflow that runs on a schedule and triggers acceptance tests in Sandbox environment
name: Scheduled acceptance tests in Sandbox environment

on:
  schedule:
    # cron that runs every 1 hour between 10 and 20 (UTC)
    - cron: "0 7-19/1 * * *"

jobs:
  scheduled-acceptance-tests:
    uses: ./.github/workflows/acceptance-tests.yml
    with:
      notify_slack_on_failure: true
      checkout_ref: main
    secrets:
      tl_client_id: ${{ secrets.ACCEPTANCE_TEST_CLIENT_ID }}
      tl_client_secret: ${{ secrets.ACCEPTANCE_TEST_CLIENT_SECRET }}
      tl_signing_key_id: ${{ secrets.ACCEPTANCE_TEST_SIGNING_KEY_ID }}
      tl_signing_private_key: ${{ secrets.ACCEPTANCE_TEST_SIGNING_PRIVATE_KEY }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL}}