# Main workflow that runs on the main branch.
# Triggered by pushes on the main branch (excluding tags).
# Build, test, run coverage analysis and release to Maven Central a final release.
name: Workflow on main branch

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  build-test-coverage:
    uses: ./.github/workflows/build-test-coverage.yml
    with:
      checkout_ref: ${{ github.ref }}
    secrets:
        coveralls_repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}
  acceptance-tests:
    needs: build-test-coverage
    uses: ./.github/workflows/acceptance-tests.yml
    with:
      checkout_ref: ${{ github.ref }}
    secrets:
      tl_client_id: ${{ secrets.ACCEPTANCE_TEST_CLIENT_ID }}
      tl_client_secret: ${{ secrets.ACCEPTANCE_TEST_CLIENT_SECRET }}
      tl_signing_key_id: ${{ secrets.ACCEPTANCE_TEST_SIGNING_KEY_ID }}
      tl_signing_private_key: ${{ secrets.ACCEPTANCE_TEST_SIGNING_PRIVATE_KEY }}
  release:
    name: Release to Maven Central
    runs-on: ubuntu-latest
    needs: [build-test-coverage, acceptance-tests]
    steps:
      - uses: actions/checkout@v4
        with:
          checkout_ref: ${{ github.ref }}
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Create tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.build-test-coverage.outputs.project_version }}
          tag_prefix: ''
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          generate_release_notes: true
      - name: Publish to Sonatype and Maven Central
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_GPG_KEY: ${{ secrets.SONATYPE_GPG_KEY }}
          SONATYPE_GPG_PASSPHRASE: ${{ secrets.SONATYPE_GPG_PASSPHRASE }}